"""Human-readable quality report generation."""

from __future__ import annotations

from datetime import UTC, datetime

from .profiler import DatasetProfile


def build_markdown_report(file_name: str, profile: DatasetProfile) -> str:
    """Render a portable Markdown report from a dataset profile."""
    lines = [
        f"# Data Quality Report: {file_name}",
        "",
        f"Generated by Open Data Scientist on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}.",
        "",
        "## Dataset overview",
        "",
        f"- Rows: **{profile.rows:,}**",
        f"- Columns: **{profile.columns:,}**",
        f"- Missing cells: **{profile.missing_cells:,}**",
        f"- Duplicate rows: **{profile.duplicate_rows:,}**",
        f"- Quality score: **{profile.health_score}/100**",
        "",
        "## Quality findings",
        "",
    ]
    if not profile.issues:
        lines.append("No automatic quality warnings were detected.")
    else:
        for issue in profile.issues:
            location = f" — `{issue.column}`" if issue.column else ""
            lines.append(f"- **{issue.severity.upper()} · {issue.title}**{location}: {issue.detail}")

    lines.extend(["", "## Column profile", "", "| Column | Type | Missing | Missing % | Unique |", "|---|---:|---:|---:|---:|"])
    for _, row in profile.column_profile.iterrows():
        lines.append(
            f"| {row['column']} | {row['dtype']} | {int(row['missing_count']):,} | "
            f"{float(row['missing_percent']):.2f}% | {int(row['unique_count']):,} |"
        )
    lines.extend(["", "---", "Open Data Scientist provides automated guidance, not a substitute for domain review."])
    return "\n".join(lines)

