[theme]
base = "light"
primaryColor = "#15803d"
backgroundColor = "#f7f3e7"
secondaryBackgroundColor = "#efe9d6"
textColor = "#16281e"
font = "sans serif"

[server]
maxUploadSize = 25

[browser]
gatherUsageStats = false
